export const RUNTIME_DB_SCHEMA = {
  services: {
    collection: 'services',
    description: 'Ephemeral Orbkit runtime heartbeats and capability metadata.',
    ttl: 'Treat records as stale when updatedAt is older than the runtime heartbeat window.',
    columns: {
      service: 'string primary key',
      role: 'string not null',
      status: 'string not null',
      metadata: 'string/json nullable',
      connectedAt: 'string not null',
      updatedAt: 'string not null indexed',
      expiresAt: 'string nullable indexed',
    },
  },
  messages: {
    collection: 'messages',
    description: 'Reusable service command mailbox slots keyed by owner/project/channel/target.',
    ttl: 'Overwrite on each command for the same owner/project/channel/target.',
    columns: {
      key: 'string primary key',
      ownerKey: 'string not null indexed',
      projectKey: 'string nullable indexed',
      channel: 'string not null indexed',
      service: 'string not null indexed',
      target: 'string nullable indexed',
      body: 'string not null',
      direction: 'string not null',
      network: 'string nullable indexed',
      createdAt: 'string not null indexed',
      expiresAt: 'string nullable indexed',
    },
  },
  funding: {
    collection: 'funding',
    description: 'Latest devnet topup state per user/address slot.',
    ttl: 'Overwrite on each funding progress update for the same user/address.',
    columns: {
      key: 'string primary key',
      ownerKey: 'string not null indexed',
      requestId: 'string indexed',
      phase: 'string not null indexed',
      status: 'string not null indexed',
      address: 'string not null indexed',
      amountInCKB: 'string not null',
      service: 'string not null',
      target: 'string nullable',
      txHash: 'string nullable',
      message: 'string not null',
      error: 'string nullable',
      result: 'json/jsonb nullable',
      createdAt: 'string not null indexed',
      expiresAt: 'string nullable indexed',
    },
  },
  structures: {
    collection: 'structures',
    description: 'Latest project structure state per user/project.',
    ttl: 'Long-lived enough for reload; overwritten by each fresh structure sync for the same user/project.',
    columns: {
      key: 'string primary key',
      ownerKey: 'string not null indexed',
      projectKey: 'string not null indexed',
      streamId: 'string not null',
      contractPath: 'string not null indexed',
      service: 'string not null indexed',
      target: 'string nullable',
      status: 'string not null',
      liveSyncEnabled: 'boolean not null',
      syncMode: 'string not null',
      changeType: 'string not null',
      sequence: 'number not null',
      message: 'string not null',
      error: 'string nullable',
      snapshot: 'json/string nullable',
      createdAt: 'string not null',
      updatedAt: 'string not null indexed',
    },
  },
  builds: {
    collection: 'builds',
    description: 'Latest build/deploy workflow state per user/project/action.',
    ttl: 'Overwrite on each progress update for the same user/project/action.',
    columns: {
      key: 'string primary key',
      ownerKey: 'string not null indexed',
      projectKey: 'string nullable indexed',
      requestId: 'string indexed',
      action: 'string not null indexed',
      status: 'string not null indexed',
      phase: 'string not null indexed',
      service: 'string not null',
      target: 'string nullable',
      network: 'string nullable indexed',
      contractPath: 'string nullable indexed',
      scriptName: 'string nullable',
      message: 'string not null',
      error: 'string nullable',
      result: 'json/string nullable',
      createdAt: 'string not null indexed',
      expiresAt: 'string nullable indexed',
    },
  },
  deployments: {
    collection: 'deployments',
    description: 'Latest durable deployment receipt per user/project/network/contract.',
    ttl: 'Long-lived; overwritten when a contract is redeployed.',
    columns: {
      key: 'string primary key',
      ownerKey: 'string not null indexed',
      projectKey: 'string not null indexed',
      service: 'string nullable indexed',
      network: 'string not null indexed',
      contractPath: 'string not null indexed',
      scriptName: 'string nullable',
      txHash: 'string nullable',
      deployAddress: 'string nullable',
      walletAddress: 'string nullable',
      receipt: 'json/jsonb not null',
      deployedAt: 'string nullable',
      updatedAt: 'string not null indexed',
    },
  },
};

export function describeRuntimeSchema() {
  return RUNTIME_DB_SCHEMA;
}
